### PR TITLE
Allow Arc and Rc cacti to be used in a single binary

### LINKED ISSUE #15: std::sync::Arc version for multithreading
Really neat crate. This is exactly what I needed for a project. Unfortunately cactus uses `std::rc::Rc` with no option for `std::sync::Arc`.

It'd be really nice if Cactus provided two versions. One built on `Rc` and another built on `Arc`.

### PR DESCRIPTION
**Pull request by ltratt**
This adapts the idea from [this forum post](https://users.rust-lang.org/t/support-both-rc-and-arc-in-a-library/40563/6) to the `cactus` library. It fixes https://github.com/softdevteam/cactus/issues/15 in a more elegant way than https://github.com/softdevteam/cactus/pull/16.

### CODE REVIEW

**Comment by forrestthewoods** [comment]
Looks good to me!

I might personally use a new alias such as `RefCount` for both `std::rc::Rc` and `std::sync::Arc`. But the approach looks good and is a solid improvement.

**Comment by ltratt** [comment]
> I might personally use a new alias such as RefCount for both std::rc::Rc and std::sync::Arc

Good point. Fixed in https://github.com/softdevteam/cactus/pull/18/commits/51a9799147ddd425fb698e70f192735a982f7c31.

@vext01 I think this is ready for consideration for inclusion now.

**Comment by vext01** [comment]
This looks sensible to me.

I was going to say: do we need to test the new `Arc` variant? But I don't know what you'd test really... If we assume `Arc` is good, there's nothing to test :P

If you are ready, please squash.

**Comment by ltratt** [comment]
Both variants are tested with `cargo test`: from Rust's perspective, after inclusion, there are two totally separate modules:

```
$ cargo test
   Compiling cactus v1.0.5 (/home/ltratt/scratch/softdev/cactus)
    Finished test [unoptimized + debuginfo] target(s) in 2.06s
     Running target/debug/deps/cactus-23bd524a6c7db5d3

running 14 tests
test arc_cactus::tests::test_debug ... ok
test arc_cactus::tests::test_hash ... ok
test arc_cactus::tests::test_eq ... ok
test arc_cactus::tests::test_simple ... ok
test arc_cactus::tests::test_try_unwrap ... ok
test arc_cactus::tests::test_vals ... ok
test rc_cactus::tests::test_eq ... ok
test rc_cactus::tests::test_debug ... ok
test arc_cactus::tests::test_vals_nodes ... ok
test rc_cactus::tests::test_hash ... ok
test rc_cactus::tests::test_simple ... ok
test rc_cactus::tests::test_try_unwrap ... ok
test rc_cactus::tests::test_vals ... ok
test rc_cactus::tests::test_vals_nodes ... ok

test result: ok. 14 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests cactus

running 16 tests
test src/raw_cactus.rs - arc_cactus::Cactus<T>::is_empty (line 26) ... ok
test src/lib.rs -  (line 10) ... ok
test src/raw_cactus.rs - arc_cactus::Cactus<T>::child (line 45) ... ok
test src/lib.rs -  (line 23) ... ok
test src/raw_cactus.rs - arc_cactus::Cactus<T>::nodes (line 96) ... ok
test src/raw_cactus.rs - arc_cactus::Cactus<T>::parent (line 64) ... ok
test src/raw_cactus.rs - arc_cactus::Cactus<T>::val (line 82) ... ok
test src/raw_cactus.rs - arc_cactus::Cactus<T>::try_unwrap (line 127) ... ok
test src/raw_cactus.rs - rc_cactus::Cactus<T>::is_empty (line 26) ... ok
test src/raw_cactus.rs - arc_cactus::Cactus<T>::vals (line 111) ... ok
test src/raw_cactus.rs - rc_cactus::Cactus<T>::nodes (line 96) ... ok
test src/raw_cactus.rs - rc_cactus::Cactus<T>::child (line 45) ... ok
test src/raw_cactus.rs - rc_cactus::Cactus<T>::parent (line 64) ... ok
test src/raw_cactus.rs - rc_cactus::Cactus<T>::val (line 82) ... ok
test src/raw_cactus.rs - rc_cactus::Cactus<T>::try_unwrap (line 127) ... ok
test src/raw_cactus.rs - rc_cactus::Cactus<T>::vals (line 111) ... ok

test result: ok. 16 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

I don't think I can sensibly squash this, so merge as-is works for me.

**Comment by vext01** [comment]
> Both variants are tested with cargo test.

Sure, but I meant, do we need any tests that use threads for concurrent access to the same cactus? I don't think there's any real need...

**Comment by ltratt** [comment]
Ah! I think we have to assume that `Arc` doesn't have multi-threading bugs :)

**Comment by vext01** [comment]
Agreed.

bors r+

**Pull request merged**
