### PR TITLE
Add bors/buildbot support.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
@vext01 I think this one is OK now.

**Comment by vext01** [comment]
Did you want to squash?

**Comment by ltratt** [comment]
I think it's best left as-is.

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
@vext01 I have no idea why it timed out, but I guess we should just try again and cross our fingers?

**Pull request merged**
